---
- name: Laboratorio Socius
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    Edad: ''
    nombre: ''

  tasks:
    - name: Imprimir la salida
      debug:
        msg: "nombre es: {{ nombre }} y tengo {{ Edad }}"
